### ISSUE TITLE
Java interop and metamodel multiple constructors runtime error

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon.language#525]
There are two constructors in java.util.UUID.   I created an object that takes a generic type and I pass a java.util.UUID to it, and then attempt to invoke the metamodel to view its type name.  This fails because there are two constructors in java.util.UUID.

Here's the sample code:

``` ceylon
import ceylon.language.meta.model {
    Type,
    ClassOrInterface
}

import java.util {
    UUID{fromString}
}

"Run the module `metamodel`."
shared void run() {
    print(WithType(fromString("5DDC5DD8-A47E-48B5-B17F-52B429F36EDA")).name);
}

class WithType<in ValueType>(ValueType type) given ValueType satisfies Object {
    shared String name {
        Type<ValueType> type = `ValueType`;

        if (is ClassOrInterface<ValueType> type) {   
            return type.string;
        }

        return "";
    }
}
```

On the return line results in the following runtime exception:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:100)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
    at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: More than one constructor found for: class java.util.UUID, 1st: private java.util.UUID(byte[]), 2nd: public java.util.UUID(long,long)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1449)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1444)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.initConstructor(AppliedClass.java:128)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.init(AppliedClass.java:78)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.checkInit(AppliedClassOrInterface.java:72)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.getDeclaration(AppliedClassOrInterface.java:110)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.getDeclaration(AppliedClass.java:65)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.getDeclaration(AppliedClass.java:30)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.toTypeString(Metamodel.java:1163)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.toString(AppliedClassOrInterface.java:1140)
    at metamodel.WithType.getName(run.ceylon:20)
    at metamodel.run_.run(run.ceylon:12)
    at metamodel.run_.main(run.ceylon)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:58)
    at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
    at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:94)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:155)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:139)
    at ceylon.modules.Main.execute(Main.java:69)
    at ceylon.modules.Main.main(Main.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.jboss.modules.Module.run(Module.java:312)
    at org.jboss.modules.Main.main(Main.java:460)
    at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:208)
    at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
    at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
    ... 7 more
```

**Comment by tombentley** [comment]
#293 has now been deferred to 1.3, so I guess we should defer this too.
