### ISSUE TITLE
Assertion when testing with manually set TCCL

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon.language#563]
Found when solving https://github.com/ceylon/ceylon-sdk/issues/249

Full code:
```ceylon
class A(){}

test
shared void run() {
	
	Thread.currentThread().contextClassLoader = javaClass<A>().classLoader;
	
    ClassLoader cl = Thread.currentThread().contextClassLoader;
    InputStream? istream = cl.getResourceAsStream("org/app5/text.txt");
    print("Classloader: ``cl``");
    print("Resource: ``istream else "<null>"``");
    assert(exists istream);
}
Thread.currentThread().contextClassLoader = javaClass<A>().classLoader;
```
`resource/org/app5/text.txt/ is an (empty) file.
In shell, it fails about half the time with:
```
$ ceylon test org.app5/1.0.0
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: ceylon.language.AssertionError "Assertion failed
	violated exists m = modules.find(moduleNameAndVersion[0], moduleNameAndVersion[1])"
	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:61)
	at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:39)
	at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:58)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:99)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:144)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:208)
	at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:172)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
	... 8 more
```

**Comment by tombentley** [comment]
I cannot reproduce this, though it's not clear to me what the last line of your example `Thread.currentThread().contextClassLoader = javaClass<A>().classLoader;` is doing there (it's not legal syntax). @jpragey could you try to reproduce? If you manage I'd be grateful if you could publish a zip somewhere of the project. Thanks.

**Comment by jpragey** [comment]
Seems that this bug vanished.
(And the last line was probably a cut/past error).
For me it's OK to close.
