### ISSUE TITLE
assertThatException(..).hasType(..) does not work when types involved have a particular signature

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon.language#570]
Originally reported here ceylon/ceylon-sdk#313 by @renatoathaydes. Unfortunately, I wasn't able to reproduce it.

---

The following code:

``` ceylon
shared test void runThis() {
    class ForbiddenInvokationException(
        String message = "",
        Exception? exception = null)
            extends Exception(message, exception) {}

    function willThrow() {
        throw ForbiddenInvokationException();
    }

    assertThatException(willThrow).hasType(`ForbiddenInvokationException`);
}
```

Fails with this Exception (interestingly, if this is run as a normal Ceylon function, not as a test, it works fine):

**EDIT**: actually, the above code works. I could not simplify it enough to still reproduce. I really tried! Sorry... the offending code is in this test: https://github.com/renatoathaydes/ConcurrenCey/blob/master/test/concurrencey/schedulerTest.ceylon#L92

Hope you can find a way to reproduce it without having to setup my whole project on your side!

Updated Exception and stack-trace:

```
com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Class has more than one overloaded constructor
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1448)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1443)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClass.init(FreeClass.java:56)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.checkInit(FreeClassOrInterface.java:139)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.getTypeParameterDeclarations(FreeClassOrInterface.java:325)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getTypeArguments(Metamodel.java:1089)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.init(AppliedClassOrInterface.java:83)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.init(AppliedClass.java:71)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.checkInit(AppliedClassOrInterface.java:72)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.getDeclaration(AppliedClassOrInterface.java:110)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.getDeclaration(AppliedClass.java:65)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClass.equals(AppliedClass.java:501)
    at ceylon.test.ExceptionAssert.hasType(assertions.ceylon:150)
    at concurrencey.SchedulerTest.exceptionIsThrownIfSchedulingTaskOnShutDownScheduler(schedulerTest.ceylon:95)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.$call$(AppliedFunction.java:247)
    at com.redhat.ceylon.compiler.java.Util.apply(Util.java:1349)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.apply(Metamodel.java:1412)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.apply(AppliedFunction.java:399)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.memberInvoke(FreeFunction.java:288)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.memberInvoke(FreeFunction.java:273)
    at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.memberInvoke(FreeFunction.java:265)
    at ceylon.test.core.DefaultTestExecutor.invokeFunction$priv$(DefaultTestExecutor.ceylon:231)
    at ceylon.test.core.DefaultTestExecutor.access$100(DefaultTestExecutor.ceylon:227)
    at ceylon.test.core.DefaultTestExecutor$4.$call$(DefaultTestExecutor.ceylon:196)
    at ceylon.test.core.DefaultTestExecutor$2.$call$(DefaultTestExecutor.ceylon:163)
    at ceylon.test.core.DefaultTestExecutor$3.$call$(DefaultTestExecutor.ceylon:170)
    at ceylon.test.core.DefaultTestExecutor$1.$call$(DefaultTestExecutor.ceylon:146)
    at ceylon.test.core.DefaultTestExecutor.execute(DefaultTestExecutor.ceylon:32)
    at ceylon.test.internal.GroupTestExecutor$1$1.next(executors.ceylon:29)
    at ceylon.language.Array.createArrayFromIterable(Array.java:73)
    at ceylon.language.Array.<init>(Array.java:57)
    at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:248)
    at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
    at ceylon.test.internal.GroupTestExecutor.execute(executors.ceylon:29)
    at ceylon.test.core.DefaultTestRunner$5$1.next(DefaultTestRunner.ceylon:60)
    at ceylon.language.Array.createArrayFromIterable(Array.java:73)
    at ceylon.language.Array.<init>(Array.java:57)
    at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:248)
    at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
    at ceylon.test.core.DefaultTestRunner.run(DefaultTestRunner.ceylon:60)
    at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:87)
    at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:39)
    at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:58)
    at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
    at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:101)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:167)
    at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:151)
    at ceylon.modules.Main.execute(Main.java:69)
    at ceylon.modules.Main.main(Main.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.modules.Module.run(Module.java:312)
    at org.jboss.modules.Main.main(Main.java:460)
    at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:208)
    at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:172)
    at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
    at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
    at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
    at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
```

**Comment by tombentley** [comment]
I can't reproduce this and the linked-to github project gives me a 404. Looking at the stacktrace it seems the exception would happen when a `Class` had a abstraction constructor with more than one overload. In theory that should never happen with a Ceylon `Exception`. Maybe the `Exception` in the code above is not `ceylon.language::Exception`, but something else (though it can't be `java.lang.Exception` because the typechecker prevents the `import` of that).

Anyway, I need more info on this one @renatoathaydes.

**Comment by tombentley** [comment]
Ah ha, notice that this is basically the same pb as #525 and thus depends on #293.

**Comment by tombentley** [comment]
Deferring to 1.3, since #293 is.
