### ISSUE TITLE
getMethods pukes on methods that have annotations with enumerated type arguments

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon.language#610]
This code:
```ceylon
import ceylon.language.meta { type }

shared interface Enum of a {}
object a satisfies Enum {}

shared final annotation class MyAnnotation(shared Enum e = a)
        satisfies OptionalAnnotation<MyAnnotation, Annotated> {}

shared annotation MyAnnotation myAnnotation() => MyAnnotation();

object annotateMe {
    myAnnotation
    shared void myMethod() {
        type(this).getMethods<Nothing>(`MyAnnotation`);
    }
}

void run() {
    annotateMe.myMethod();
}
```

Causes this:
```
Source found for module test, compiling...
Note: Created module test/0.0.1
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
Caused by: com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: While reflectively instantiating class test.MyAnnotation on element function test::annotateMe.myMethod
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1613)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.addAnnotation(Metamodel.java:942)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:996)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:982)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeNestableDeclaration.annotations(FreeNestableDeclaration.java:92)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.hasAllAnnotations(AppliedClassOrInterface.java:1131)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedClassOrInterface.getMethods(AppliedClassOrInterface.java:802)
	at test.annotateMe_.myMethod(testme.ceylon:14)
	at test.run_.run(testme.ceylon:19)
	at test.run_.main(testme.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:58)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:101)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:167)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:151)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:208)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:368)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:305)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.addAnnotation(Metamodel.java:935)
	... 36 more
Caused by: com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: java.lang.NoSuchMethodException: test.a_.get_()
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1613)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1608)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.parseEnumerationReference(Metamodel.java:1180)
	at test.MyAnnotation.<init>(testme.ceylon:6)
	... 41 more
```

**Comment by FroMage** [comment]
Fixed!
