### ISSUE TITLE
Metamodel lookup for non-local top-level object throws NPE

### ISSUE THREAD

**Issue by akberc** [ceylon/ceylon.language#629]
Not sure whether it belongs in the language or compiler module.  Given the following in a module:
```ceylon
object obj {
    shared String version = `obj`.declaration.containingModule.version;
}

shared void run() {
    print(obj.version);   
}
```
Error stack:
```
ceylon run: null
java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getProducedType(Metamodel.java:245)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.checkReifiedTypeArgument(Metamodel.java:1405)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeValue.apply(FreeValue.java:95)
	at test.obj_.<init>(run.ceylon:3)
	at test.obj_.<clinit>(run.ceylon:3)
	at test.run_.run(run.ceylon:8)
	at test.run_.main(run.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by tombentley** [comment]
This was a compiler bug. The value of the `object` was computed eagerly in a `static` block which occurs before the initialization of the `$TypeDescriptor$`, thus the `$TypeDescriptor$` is null at the point `obj` is instantiated.

Thanks for reporting.

**Comment by akberc** [comment]
Thank you for fixing.  This was just a regression.
