### ISSUE TITLE
NPE when scanning annotated classes + methods in comprehensions

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon.language#644]
Running:
``` ceylon
shared final annotation class Message() satisfies OptionalAnnotation<Message, FunctionDeclaration>{}
shared annotation Message message() => Message();

shared final annotation class MessageClass() satisfies OptionalAnnotation<MessageClass, ClassDeclaration> {}
shared annotation MessageClass messageClass() => MessageClass();


shared class MessageMethod(shared FunctionDeclaration functionDeclaration) {
    shared actual String string => functionDeclaration.string;
}


{MessageMethod *} messagesForClassDeclaration(ClassDeclaration cls) => {
    if(exists classAnno = annotations(`MessageClass`, cls))
        for(FunctionDeclaration fd in cls.declaredMemberDeclarations<FunctionDeclaration>())
            if(exists methodAnno = annotations(`Message`, fd))
                MessageMethod(fd)
    
};

shared void run() {
    [{MessageMethod *} *] v = 
        [for(cls in `package`.members<ClassDeclaration>()) 
            messagesForClassDeclaration(cls)];
    print(v);
}
```
causes:
```
ceylon run: null
java.lang.NullPointerException
	at bug.MessageMethod.toString(run.ceylon:20)
	at ceylon.language.stringify_.stringify(print.ceylon:33)
	at ceylon.language.commaList_$1$1$1.next(Iterable.ceylon:1331)
	at com.redhat.ceylon.compiler.java.language.LazyIterable$LazyIterator.next(LazyIterable.java:46)
	at ceylon.language.String.join(String.java:970)
	at ceylon.language.commaList_.commaList(Iterable.ceylon:1331)
	at ceylon.language.Iterable$impl.toString(Iterable.ceylon:1321)
	at ceylon.language.impl.BaseIterable.toString(bases.ceylon)
	at ceylon.language.stringify_.stringify(print.ceylon:33)
	at ceylon.language.commaList_$1$1$1.next(Iterable.ceylon:1331)
	at com.redhat.ceylon.compiler.java.language.LazyIterable$LazyIterator.next(LazyIterable.java:46)
	at ceylon.language.String.join(String.java:970)
	at ceylon.language.commaList_.commaList(Iterable.ceylon:1331)
	at ceylon.language.Sequential$impl.toString(Sequential.ceylon:156)
	at ceylon.language.Sequence$impl.toString(Sequence.ceylon:196)
	at ceylon.language.ArraySequence.toString(ArraySequence.ceylon)
	at ceylon.language.stringify_.stringify(print.ceylon:33)
	at ceylon.language.print_.print(print.ceylon:13)
	at bug.run_.run(run.ceylon:36)
	at bug.run_.main(run.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:411)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:348)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:113)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:40)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:33)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:26)
```

**Comment by gavinking** [comment]
Now https://github.com/ceylon/ceylon-compiler/issues/2135. Closing this one, since the problem seems to be in the JVM compiler backend.
