### ISSUE TITLE
test-js results in "Cannot read property 'annotations' of undefined"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#650]
The problem is contained somewhere in the range below (after `git revert` for the range, test-js works):

```sh
git log b13e08a48f8f32db177060bf2bdc34cb70452307..809a62275788677dda5ea89d72e2a14f9ed89126
```

The error:

```
$ ceylon test-js test.com.vasileff.ceylon.random.api
NODE_PATH=/Users/jvasileff/Dropbox/Repos/ceylon/ceylon-dist/dist/repo:/Users/jvasileff/Dropbox/Repos/jv/ceylon-random/modules:/Users/jvasileff/.ceylon/repo:/Users/jvasileff/.ceylon/cache:[Maven] Aether:/Users/jvasileff/Dropbox/Repos/jv/ceylon-random/modules
/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1286
            $39p=$39n.containingPackage.annotations({Annotation$annotations:$$
                                       ^
TypeError: Cannot read property 'annotations' of undefined
    at findAnnotation$core (/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1286:40)
    at createExecutor$core (/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:981:14)
    at createExecutors$core (/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:942:26)
    at defaultTestRunner$.$357 (/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:871:24)
    at DefaultTestRunner$core (/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:836:49)
    at Object.createTestRunner (/Users/jvasileff/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:2262:12)
    at run (/Users/jvasileff/.ceylon/repo/com/redhat/ceylon/testjs/1.1.1/com.redhat.ceylon.testjs-1.1.1.js:197:20)
    at [eval]:1:336
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

**Comment by thradec** [comment]
duplicate of ceylon/ceylon-js#515

**Comment by jvasileff** [comment]
Ok, thanks @thradec.
