### ISSUE TITLE
Overflow and Integer Ranges

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#656]
There are a few oddities on both JVM and JS for Integer ranges that are either:

1) Longer than maxIntegerValue, or
2) Extend beyond min/maxIntegerValue

Perhaps both of the following should throw, since `size` would not be accurate. On JVM, the second is descending:
```ceylon
    print((0..runtime.maxIntegerValue)[1]);  // 1
    print((-1..runtime.maxIntegerValue)[1]); // -2 on JVM, 0 on JS
```

Negative sizes on JVM:
```ceylon
    print((-1..runtime.maxIntegerValue).size); // -9223372036854775807
    print((-2..runtime.maxIntegerValue).size); // -9223372036854775808
    print((-3..runtime.maxIntegerValue).size); // 9223372036854775807
```

Incorrect sizes and infinite loops on JS:
```ceylon
    variable value range = (runtime.maxIntegerValue)..(runtime.maxIntegerValue+2);
    print(range.size); // 2 (not 3)
    printAll(range); // 9007199254740991, 9007199254740992
    
    range = (runtime.maxIntegerValue)..(runtime.maxIntegerValue+3);
    print(range.size); // 4
    printAll(range.take(10)); // 9007199254740991, 9007199254740992, 9007199254740992, ...
```

**Comment by jvasileff** [comment]
It's probably worth noting differences and behavior of measure:

```ceylon
    value range = runtime.maxIntegerValue:4;
    print(range.size);
    print(range.last);
    printAll(range);
```
JVM:
```
4
-9223372036854775806
9223372036854775807, -9223372036854775808, -9223372036854775807, -9223372036854775806
```
JS:
```
4
9007199254740994
9007199254740991, 9007199254740992, 9007199254740992, 9007199254740992
```

**Comment by gavinking** [comment]
I guess the fix to this stuff is to do some overflow checking in `Integer`'s implementation of `Enumerable`.

**Comment by gavinking** [comment]
First one, isn't it?

**Comment by gavinking** [comment]
I have pushed a proposed fix for the JVM. @chochos could you look at the JS side, please?

**Comment by jvasileff** [comment]
Should all `Ordinal` and `Enumerable` methods just throw on JS for values outside `runtime.min/maxIntegerValue` range?

It seems like the following identities should hold:

```ceylon
(x..y).size == {*(x..y)}.size
HashSet { *(x:n) }.size == n
x.successor.successor == x+2
```

In other words, `Integer` is only a reasonable candidate for `Enumerable` within the min/max range.

**Comment by jvasileff** [comment]
This:

```ceylon
    value x = runtime.maxIntegerValue-1;
    printAll(((x-4)..x).by(2));
```

now produces:

```
9223372036854775802, 9223372036854775804ceylon run: neighbour overflow
ceylon.language.OverflowException "neighbour overflow"
	at ceylon.language.Integer.neighbour(Integer.java:363)
	at ceylon.language.Integer.neighbour(Integer.java:370)
	at ceylon.language.Integer.neighbour(Integer.java:17)
	at ceylon.language.Span.nextStep$priv$(Span.ceylon:39)
	at ceylon.language.Span.access$400(Span.ceylon:1)
	at ceylon.language.Span$By$1anonymous_2_.next(Span.ceylon:282)
	at ceylon.language.printAll_.printAll(print.ceylon:25)
	at ceylon.language.printAll_.printAll(print.ceylon:22)
...
```

Also, this works, which is good:
```ceylon
    value x = runtime.maxIntegerValue-1;
    for (i in ((x-4)..x).by(2)) {
        print(i);
    }
```
but I wonder if compiler optimizations will need to be reviewed too.

**Comment by jvasileff** [comment]
Size adds 1 to the offset, so this slips through:

```ceylon
    value bigRange = 0..runtime.maxIntegerValue;
    print(bigRange.size); // -9223372036854775808
```

**Comment by jvasileff** [comment]
Now that Integer is a linear/recursive `Enumerable` hybrid, what should `Byte` and `Character` be?

```ceylon
    // recursive
    print(255.byte.successor); // (min-byte)
    print(runtime.maxIntegerValue.successor); // (min-int on JVM)

    // recursive byte, custom integer
    print(1.byte.neighbour(255)); // 0
    //print(1.neighbour(runtime.maxIntegerValue)); // overflow

    // recursive byte, linear integer
    print((1.byte..0.byte).size); // 256
    print((1..0).size); // 2
```

**Comment by jvasileff** [comment]
An ugly idea to fix `Span`'s `by`:

```diff
diff --git i/src/ceylon/language/Span.ceylon w/src/ceylon/language/Span.ceylon
index 6f60022..0bfd1ae 100644
--- i/src/ceylon/language/Span.ceylon
+++ w/src/ceylon/language/Span.ceylon
@@ -284,12 +284,19 @@ class Span<Element>(first, last)
                 return object
                         satisfies Iterator<Element> {
                     variable value current = first;
+                    variable value exhausted = false;
                     shared actual Element|Finished next() {
-                        if (containsElement(current)) {
+                        if (!exhausted && containsElement(current)) {
                             value result = current;
-                            current = nextStep(current, step);
+                            try {
+                                current = nextStep(current, step);
+                            }
+                            catch (OverflowException e) {
+                                exhausted = true;
+                            }
                             return result;
                         } else {
+                            exhausted = true;
                             return finished;
                         }
                     }
```

**Comment by jvasileff** [comment]
`Measure.ceylon`'s `By` also causes trouble:

```ceylon
    printAll((1:runtime.maxIntegerValue)
            .by(runtime.maxIntegerValue / 5));
```
throws
```
1, 1844674407370955162, 3689348814741910323, 5534023222112865484, 7378697629483820645ceylon run: neighbour overflow
ceylon.language.OverflowException "neighbour overflow"
	at ceylon.language.Integer.neighbour(Integer.java:363)
	at ceylon.language.Integer.neighbour(Integer.java:370)
	at ceylon.language.Integer.neighbour(Integer.java:17)
	at ceylon.language.Measure$By$1anonymous_1_.next(Measure.ceylon:77)
	at ceylon.language.printAll_.printAll(print.ceylon:25)
	at ceylon.language.printAll_.printAll(print.ceylon:22)
```

**Comment by gavinking** [comment]
@jvasileff wait wait wait ... we're not trying to "fix" every case of numeric overflow/loss of precision. Those problems are endemic on the VMs we target and we can't "fix" them without unacceptable loss of performance. We were only trying to fix some especially pathological behavior in ranges.

Nor are we trying to make `Integer` and `Byte` behave the same. They have quite different concepts: `Byte` is documented to represent an equivalence class and support modular-256 arithmetic, and is officially a recursive enumerable type. `Integer` isn't.

**Comment by jvasileff** [comment]
> we're not trying to "fix" every case

If you're referring to `Span.By`, I'm not seeing a statistically valid difference in performance with the extra boolean on the JVM (assuming the patch above is actually a correct fix.) For summing (0..100M).step(2) in a for loop, results in picoseconds/iter:

```
Summary min/max/avg/rstddev/pct
old      6320/9054/7565/16% (100%)
new      6393/8104/7184/9% (101%)
baseline 6446/9300/7842/14% (101%)
```

FWIW - the Span.By issue isn't one of the ones I explicitly looked for; the original overflow fix caused existing code to break.

On the wrong answers/infinite loop stuff in JS, that actually seems like a bigger concern to me - it reminds me of the type of thing that can make pagers (iMessages?) go off in the middle of the night.

> Nor are we trying to make Integer and Byte behave the same

Ok, that makes sense. And I guess Integer wasn’t really recursive in span before (it was more like shortest-path) making half of the basis for my question invalid anyway.

**Comment by gavinking** [comment]
@jvasileff OK, well I'm not really against applying your patch to `Span.By` it's just that I'm sure there's still other spots where stuff can overflow, including in `Integer.successor` and `Integer.predecessor` and I don't think we've really tracked them all down...

**Comment by tombentley** [comment]
Well over in https://github.com/ceylon/ceylon-compiler/issues/2130 I'm trying to fix the existing loop optimizations for span and measure. Maybe I should stop until we've fixed this stuff because getting this stuff right in the optimization takes longer than "simply" fixing things like `Span.By`.

**Comment by gavinking** [comment]
@tombentley well which overflow scenarios do you have?

**Comment by tombentley** [comment]
Well @gavinking there are a few. I want to ensure that the optimized code behaves the same as the non optimized code even for these edge cases where stuff throws so that

    for(i in start:length) {}
    // behaves the same as
    value iterable = start:length;
    for(i in iterable) {}

for all `start` and `length` with "the same" exceptions (excluding stacktraces) being thrown after the same number of iterations.

I'm trying to cover `start:length`, `(start:length).by(step)`, `first..last` and `(first..last).by(step)`. 

The cases are:

* overflow of `start+length` in a measure
* `length <= 0` in a measure
* `step <= 0` in either measure or span
* overflow during iteration (e.g. `first+step` or `first+1`, or `start+1`)
* `last-first` overflow in a span

I've mostly got it working (though I've had to change the `By` iterables because they were eagerly computing their next value while returning their current which wasn't very amenable to turning into a C-style `for` loop. But it remains to be seen how much of an optimization these things are now, because I have to use `offset()` and `neighbour()` sometimes in order to throw exceptions rather than overflow.

**Comment by gavinking** [comment]
Well, OK, so all those sound OK, we just need to make sure that the definitions in `Span` and `Measure` do the same thing you're doing.

**Comment by jvasileff** [comment]
Until recently, the optimized

```ceylon
    value max = runtime.maxIntegerValue;
    for (i in (max-4..max).by(2)) {
        print(i);
    }
```
worked, and the non-optimized threw an OverflowException. Now, they both throw. Any reason not to have them both work?

**Comment by gavinking** [comment]
Well, what change is this related to?

**Comment by jvasileff** [comment]
I'm not aware of any purely linear `Enumerable`s. So for sake of argument, imagine a linear enumerable `Month` of january..december.

What should this
```ceylon
printAll((september..december).by(2));
```
produce?

1. "september, november"
2. "september, november, december" (since max.successor == sucessor)
3. "september, november" + OverflowException

**Comment by jvasileff** [comment]
> Well, what change is this related to?

Both `Span.ceylon` and the compiler (ceylon/ceylon-compiler#2130) have been in flux.

**Comment by tombentley** [comment]
@jvasileff please note that ceylon/ceylon-compiler#2130 isn't finished yet.

**Comment by jvasileff** [comment]
@tombentley I understand. I just wanted to weigh in before it was too late :)

**Comment by luolong** [comment]
The way I understand ranges and spans, 
```ceylon
printAll((september..december));
// prints "september, october, november, december"

printAll((september..december).by(2));
// should therefore print "september, november" (every 2n-1 element)
```

**Comment by jvasileff** [comment]
@luolong that makes sense to me. But then, how should it be implemented? Assuming `by` is implemented in terms of `Enumerable.neighbour`, and satisfying the contract for `Ordinal.successor`, I think we'd have:

```ceylon
    print(november.neighbour(1)); // december
    print(november.neighbour(2)); // OverflowException
    print(december.neighbour(1)); // OverflowException

    print(november.successor); // december
    print(december.successor); // december    
```

with `OverflowException` being a possible addition to the contract for `Enumerable.neighbour`.

**Comment by luolong** [comment]
I would think that throwing exceptions is not very Ceylonic. Unless those are assertion errors that is ...

**Comment by jvasileff** [comment]
I agree, it's not pretty.  `AssertionError` wouldn't be right though, since there is no way for the caller to know if `neighbor(2)` is valid.

**Comment by FroMage** [comment]
Moving to 1.3.
