### ISSUE TITLE
apply() doesn't always narrow tuple types correctly.

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon.language#675]
Observe:
```ceylon
import ceylon.collection { ArrayList }
import ceylon.language.meta { type }
import ceylon.language.meta.model { Function }

shared [K+] sequence<K>(K+ ret) => ret;

shared void tester([String *] k) => print(k);

shared void run() {
    [String+] k = [ "hi", "hello" ];
    value l = ArrayList<Object?>{ "hi", "hello" };
    value s = `sequence<String>`;
    
    print(s.type); // ceylon.language::Sequence<ceylon.language::String>
    print(type(s.apply(*k))); // ceylon.language::Tuple<ceylon.language::String,ceylon.language::String,ceylon.language::Tuple<ceylon.language::String,ceylon.language::String,ceylon.language::empty>>
    print(type(s.apply(*l))); // ceylon.language::ArraySequence<ceylon.language::Null|ceylon.language::Object>
    tester(s.apply(*k)); // [hi, hello]
    tester(s.apply(*l)); // [hi, hello]
    `tester`.apply(s.apply(*k)); // [hi, hello]
    `tester`.apply(s.apply(*l)); // ******** CRASH *********
}

/*
ceylon.language.meta.model.IncompatibleTypeException "Invalid argument 0, expected type Type[String[]] but got Type[ArraySequence<Object?>]"
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.apply(Metamodel.java:1684)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.AppliedFunction.apply(AppliedFunction.java:403)
	at tmp.run_.run(tmp.ceylon:22)
	at tmp.run_.main(tmp.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
*/
```

**Comment by jvasileff** [comment]
Oh, interesting. So `apply` called on a variadic correctly checks the type of each item, but the sequential it pass to the target method is not of the correct reified type.

I think this shows the same problem:

```ceylon
[K+] seq<K>(K+ ret) {
    print("-- " + type(ret).string);
    assert((ret of Anything) is [K+]);
    return ret;
}

shared void runTest() {
    [<Integer|String>*] l = { 1, "hi", "hello" }.sequence().rest;
    value s = `seq<String>`;
    s.apply(*l);
}
```
producing:
```
-- ceylon.language::ArraySequence<ceylon.language::Integer|ceylon.language::String>
Exception in thread "main" ceylon.language.AssertionError "Assertion failed
	violated (ret of Anything) is [K+]"
```

The same happens with a non-generic `[String+] seqs(String+ ret) { ... }`

**Comment by FroMage** [comment]
Right, so either `apply` should throw, or it should wrap and copy the spread sequence being passed.

**Comment by FroMage** [comment]
Fixed: `apply` will now wrap/copy the arguments passed, but `namedApply` will throw because there's no implicit spreading possible, so we _can_ check the argument types entirely (rather than element by element).
