### ISSUE TITLE
Weird metamodel exception trying to run tests

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon.language#679]
```
[sadmac@baudrillard ceylon.parse (master)]$ ceylon test test.ceylon.parse
Exception in thread "main" com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Declaration type not supported yet: UnknownType
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1707)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1702)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:606)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getAppliedMetamodel(Metamodel.java:347)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates.isDeclarationAnnotatedWith(Predicates.java:360)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreePackage.annotatedMembers(FreePackage.java:123)
	at ceylon.test.core.findCandidatesInPackage_.findCandidatesInPackage(DefaultTestRunner.ceylon:196)
	at ceylon.test.core.findCandidatesInModule_.findCandidatesInModule(DefaultTestRunner.ceylon:191)
	at ceylon.test.core.findCandidates_.findCandidates(DefaultTestRunner.ceylon:171)
	at ceylon.test.core.createExecutors_.createExecutors(DefaultTestRunner.ceylon:85)
	at ceylon.test.core.DefaultTestRunner.initExecutors$priv$(DefaultTestRunner.ceylon:43)
	at ceylon.test.core.DefaultTestRunner.<init>(DefaultTestRunner.ceylon:46)
	at ceylon.test.createTestRunner_.createTestRunner(TestRunner.ceylon:49)
	at ceylon.test.createTestRunner_.createTestRunner(TestRunner.ceylon)
	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:85)
	at com.redhat.ceylon.testjvm.run_.run(tool.ceylon:36)
	at com.redhat.ceylon.testjvm.run_.main(tool.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
	at ceylon.modules.bootstrap.CeylonTestTool.run(CeylonTestTool.java:173)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.redhat.ceylon.launcher.Bootstrap.run(Bootstrap.java:55)
	at com.redhat.ceylon.launcher.Bootstrap.main(Bootstrap.java:32)
```

**Comment by lucaswerkmeister** [comment]
```ceylon
import ceylon.test {
    test,
    TestAnnotation
}
import ceylon.language.meta.declaration {
    FunctionDeclaration
}
test
shared void run() {
    print(`package ceylon.language`.annotatedMembers<FunctionDeclaration,TestAnnotation>());
}
```
produces the same error.

**Comment by lucaswerkmeister** [comment]
However, no error happens if I replace `TestAnnotation` with `SharedAnnotation` or some custom annotation defined in the same module. Might be a model loader issue.

**Comment by lucaswerkmeister** [comment]
> at ….Metamodel.getAppliedMetamodel([Metamodel.java:578](https://github.com/ceylon/ceylon.language/blob/c10748f896c70aca3a9c5e6f2870317461e4e306/runtime/com/redhat/ceylon/compiler/java/runtime/metamodel/Metamodel.java#L578))
at ….Metamodel.getAppliedMetamodel([Metamodel.java:317](https://github.com/ceylon/ceylon.language/blob/c10748f896c70aca3a9c5e6f2870317461e4e306/runtime/com/redhat/ceylon/compiler/java/runtime/metamodel/Metamodel.java#L317))

The outer (lower) `getAppliedMetaModel` is trying to get the metamodel of `TestAnnotation`. The inner (upper) one is called with `Type[unknown]`, which fails.

**Comment by lucaswerkmeister** [comment]
This code fails with the same error (different stacktrace of course):
```ceylon
import ceylon.test {
    TestAnnotation
}
shared void run() {
    print(`TestAnnotation`);
}
```
I think `TestAnnotation` isn’t being initialized correctly, `getProducedType` returns `UnknowType`.

**Comment by lucaswerkmeister** [comment]
`` `class TestState` `` from `ceylon.test` works, seems to be restricted to annotation classes.

**Comment by lucaswerkmeister** [comment]
This *might* be a Java 8-only issue. Both @sadmac7000 and I are on Java 8, and I was able to run `ceylon.formatter` tests successfully on my server this morning (Debian Wheezy → Java 7).

**Comment by jvasileff** [comment]
In case it helps, `ant clean test` on `ceylon.formatter` passes for me on both Java 7 & 8, with Ceylon compiled with Java 7.

**Comment by lucaswerkmeister** [comment]
I just rebuilt my Ceylon + `ceylon.formatter` with Java 7 and it still fails.

**Comment by lucaswerkmeister** [comment]
Works after an `ant clean publish` in `ceylon-sdk`. Probably fallout from an already fixed compiler bug.

**Comment by sadmac7000** [comment]
Works for me now as well. I think this is solved.
