### ISSUE TITLE
ModelResolutionException: Failed to resolve ceylon.language.loop_$1iterable_

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon.language#686]
Since #685 was merged, I’m getting this test failure in `ceylon.ast`:
```
[ceylon-test] running: test.ceylon.ast.core::characterLiteralCeylonExpression
# […]
[ceylon-test] running: test.ceylon.ast.core::testEditor
[ceylon-test] running: test.ceylon.ast.create::annotations
# […]
[ceylon-test] running: test.ceylon.ast.create::typeParameters
[ceylon-test] running: test.ceylon.ast.redhat::addAssignmentOperation
[ceylon-test] com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.loop_$1iterable_
[ceylon-test] 	at com.redhat.ceylon.model.loader.AbstractModelLoader.convertToDeclaration(AbstractModelLoader.java:1431)
[ceylon-test] 	at com.redhat.ceylon.model.loader.AbstractModelLoader.addLocalDeclarations(AbstractModelLoader.java:2278)
[ceylon-test] 	at com.redhat.ceylon.model.loader.AbstractModelLoader.complete(AbstractModelLoader.java:3524)
[ceylon-test] 	at com.redhat.ceylon.model.loader.model.LazyMethod.load(LazyMethod.java:82)
[ceylon-test] 	at com.redhat.ceylon.model.loader.model.LazyMethod.getTypeParameters(LazyMethod.java:117)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.<init>(FreeFunction.java:51)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getOrCreateMetamodel(Metamodel.java:341)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:345)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:330)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$And.accept(Predicates.java:117)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreePackage.filteredMembers(FreePackage.java:138)
[ceylon-test] 	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreePackage.annotatedMembers(FreePackage.java:125)
[ceylon-test] 	at ceylon.test.core.doFindCallbacks_.doFindCallbacks(DefaultTestExecutor.ceylon:265)
[ceylon-test] 	at ceylon.test.core.callbackCache_.get(DefaultTestExecutor.ceylon:280)
[ceylon-test] 	at ceylon.test.core.doFindCallbacks_$2.$call$(DefaultTestExecutor.ceylon:260)
[ceylon-test] 	at ceylon.test.core.doFindCallbacks_$1visit_.visit(DefaultTestExecutor.ceylon:241)
[ceylon-test] 	at ceylon.test.core.doFindCallbacks_$1visit_.visit(DefaultTestExecutor.ceylon:244)
[ceylon-test] 	at ceylon.test.core.doFindCallbacks_$1visit_.visit(DefaultTestExecutor.ceylon:247)
[ceylon-test] 	at ceylon.test.core.doFindCallbacks_.doFindCallbacks(DefaultTestExecutor.ceylon:257)
[ceylon-test] 	at ceylon.test.core.callbackCache_.get(DefaultTestExecutor.ceylon:280)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.findCallbacks$priv$(DefaultTestExecutor.ceylon:223)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.verifyBeforeCallbacks(DefaultTestExecutor.ceylon:106)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.verify(DefaultTestExecutor.ceylon:50)
[ceylon-test] 	at ceylon.test.core.DefaultTestExecutor.execute(DefaultTestExecutor.ceylon:26)
[ceylon-test] 	at ceylon.test.internal.GroupTestExecutor$1$1.next(executors.ceylon:29)
[ceylon-test] 	at ceylon.language.Array.createArrayFromIterable(Array.java:150)
[ceylon-test] 	at ceylon.language.Array.<init>(Array.java:100)
[ceylon-test] 	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:232)
[ceylon-test] 	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
[ceylon-test] 	at ceylon.test.internal.GroupTestExecutor.execute(executors.ceylon:29)
[ceylon-test] 	at ceylon.test.core.DefaultTestRunner$5$1.next(DefaultTestRunner.ceylon:60)
[ceylon-test] 	at ceylon.language.Array.createArrayFromIterable(Array.java:150)
[ceylon-test] 	at ceylon.language.Array.<init>(Array.java:100)
[ceylon-test] 	at ceylon.language.Iterable$impl.sequence(Iterable.ceylon:232)
[ceylon-test] 	at ceylon.language.impl.BaseIterable.sequence(bases.ceylon)
[ceylon-test] 	at ceylon.test.core.DefaultTestRunner.run(DefaultTestRunner.ceylon:60)
[ceylon-test] 	at com.redhat.ceylon.testjvm.Runner.run(tool.ceylon:85)
[ceylon-test] 	# […]
[ceylon-test] running: test.ceylon.ast.redhat::addAssignmentOperation.conversion
[ceylon-test] running: test.ceylon.ast.redhat::aliasDec
[ceylon-test] running: test.ceylon.ast.redhat::aliasDec.compilation
[ceylon-test] running: test.ceylon.ast.redhat::aliasDec.conversion
[ceylon-test] running: test.ceylon.ast.redhat::andAssignmentOperation
[ceylon-test] running: test.ceylon.ast.redhat::andAssignmentOperation.compilation
[ceylon-test] running: test.ceylon.ast.redhat::andAssignmentOperation.conversion
# […]
[ceylon-test] running: test.ceylon.ast.samples.turingMachine::powerOfTwo
[ceylon-test] ======================== TEST RESULTS ========================
[ceylon-test] run:     619
[ceylon-test] success: 619
[ceylon-test] failure: 0
[ceylon-test] error:   1
[ceylon-test] ignored: 289
[ceylon-test] time:    22s
[ceylon-test] 
[ceylon-test] test.ceylon.ast.redhat::addAssignmentOperation.compilation - error (com.redhat.ceylon.model.loader.ModelResolutionException: Failed to resolve ceylon.language.loop_$1iterable_)
[ceylon-test] 
[ceylon-test] ======================= TESTS FAILED ! =======================
```

The first test of the `test.ceylon.ast.redhat` package fails. All other tests, in that and other packages, succeed. `loop` does not appear to be used anywhere in `ceylon.ast` or `ceylon-sdk`.

If I revert c31c542, re`publish` `ceylon-dist`, and rerun (without recompile) the tests, they succeed.

**Comment by lucaswerkmeister** [comment]
```sh
~/git/ceylon $ grep -r 'loop_$1iterable_'
Binary file ceylon-ide-eclipse/required-bundle-proxies/ceylon.language-1.1.0.car/ceylon.language-1.1.0.car matches
ceylon-ide-eclipse/required-bundle-proxies/ceylon.language-1.1.0.car/META-INF/mapping.txt:ceylon/language/loop_$1iterable_.class=ceylon/language/loop.ceylon
ceylon-ide-eclipse/required-bundle-proxies/ceylon.language-1.1.0.car/META-INF/mapping.txt:ceylon/language/loop_$1iterable_$1iterator_.class=ceylon/language/loop.ceylon
Binary file ceylon-dist/osgi/defaultRepository/ceylon/language/1.1.0/ceylon.language-1.1.0.car matches
Binary file ceylon-dist/osgi/defaultRepository/ceylon/language/1.1.0/ceylon.language-1.1.0.car.idx matches
Binary file ceylon.language/ide-dist/ceylon.language-1.1.0.car matches
```
Is something trying to load `ceylon.language/1.1.0`?

**Comment by lucaswerkmeister** [comment]
> Is something trying to load ceylon.language/1.1.0?

No, that can’t be it. I’m running the tests every morning in a fresh LXC, which doesn’t have `ceylon.language/1.1.0`. In fact, in that LXC:
```sh
$ sudo lxc-start -n ceylon-ci-2015-05-28 -- grep -r 'loop_$1iterable_' /build
```
no results.

**Comment by lucaswerkmeister** [comment]
Closing, can no longer reproduce. Seems to have been fixed.
