### ISSUE TITLE
ConstructorDeclaration.annotatedConstructorDeclarations fails (CCE)

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#693]
For

```ceylon
class MyClass {
    shared new () {}
    shared new NoArg() {}
    shared new OneArg(String s) {}
}
shared void cTest() {
    `MyClass`.declaration.annotatedConstructorDeclarations<SharedAnnotation>();
}
```
you get:
```
ceylon run: com.redhat.ceylon.compiler.java.runtime.metamodel.FreeConstructor
cannot be cast to com.redhat.ceylon.compiler.java.runtime.metamodel.
FreeNestableDeclaration
java.lang.ClassCastException: com.redhat.ceylon.compiler.java.runtime.metamodel.FreeConstructor cannot be cast to com.redhat.ceylon.compiler.java.runtime.metamodel.FreeNestableDeclaration
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:345)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:330)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClass.filterConstructors(FreeClass.java:344)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClass.annotatedConstructorDeclarations(FreeClass.java:361)
	at sandbox.ceylon.snap.base.databinding.cTest_.cTest(metaModelTesting.ceylon:91)
	at sandbox.ceylon.snap.base.databinding.cTest_.main(metaModelTesting.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
```

**Comment by FroMage** [comment]
Fixed.
