### ISSUE TITLE
'Annotated.annotated<A>' throws when 'A' is not a Class

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#706]
Most methods that take an `Annotation` type argument allow any type that satisfies `Annotated` to be used. But `annotated` requires the argument to be a class:

```ceylon
shared void annoTest() {
    by("me") class Foo() {}
    print(`class Foo`.annotated<Annotation>());
}
```
results in:
```
Exception in thread "main" com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unable to find annotation class ceylon.language.Annotation$annotation$ for annotation type interface ceylon.language.Annotation
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1679)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getJavaAnnotationClass(Metamodel.java:1023)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.isAnnotated(Metamodel.java:1722)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.annotated(FreeClassOrInterface.java:515)
	at sandbox.ceylon.snap.base.databinding.annoTest_.annoTest(DataBinding.ceylon:230)
	at sandbox.ceylon.snap.base.databinding.annoTest_.main(DataBinding.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:110)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:176)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:160)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:245)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:390)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:327)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
Caused by: java.lang.ClassNotFoundException: ceylon.language.Annotation$annotation$ from [Module "ceylon.language:1.1.1" from local module loader @44825de5 (finder: local module finder @4ae28886 (roots: /Users/jvasileff/Applications/eclipse-4.4.1-ceylon/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150601-1423/repo))]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getJavaAnnotationClass(Metamodel.java:1021)
	... 32 more
```

but this works:

```ceylon
shared void annoTest() {
    by("me") class Foo() {}
    print(`class Foo`.annotations<Annotation>());
}
```

**Comment by FroMage** [comment]
Fixed.
