### ISSUE TITLE
Test running fails in JS (jvm works for same test)

### ISSUE THREAD

**Issue by simonthum** [ceylon/ceylon.language#726]
I am getting:

NODE_PATH=/home/simon/coding/ceylon/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150721-1331/repo:/home/simon/coding/ceylon/eclipse-ws/ccolor/ccalc.test/modules:/home/simon/coding/ceylon/eclipse-ws/ccolor/ccalc/modules:/home/simon/.ceylon/repo:/home/simon/.ceylon/cache:[Maven] Aether:/home/simon/coding/ceylon/eclipse-ws/ccolor/ccalc.test/modules
/home/simon/coding/ceylon/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150721-1331/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6119
if (mm.t) {
      ^
TypeError: Cannot read property 't' of undefined
    at qname$ (/home/simon/coding/ceylon/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150721-1331/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:6119:7)
    at atr$.mod [as qualifiedName] (/home/simon/coding/ceylon/eclipse/plugins/com.redhat.ceylon.dist.repo_1.1.1.v20150721-1331/repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:7672:207)
    at findCandidatesInFunction$core (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1035:57)
    at findCandidatesInFunctionLiteral$core (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1156:1)
    at findCandidatesInTypeLiteral$core (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1077:4)
    at findCandidates$core (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:1001:1)
    at createExecutors$core (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:871:10)
    at defaultTestRunner$.$367 (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:830:8)
    at DefaultTestRunner$core (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:803:45)
    at Object.createTestRunner (/home/simon/.ceylon/repo/ceylon/test/1.1.1/ceylon.test-1.1.1.js:2086:8)

**Comment by FroMage** [comment]
Can you give us some code to reproduce?

**Comment by simonthum** [comment]
I suppose it's a different variant or the problem in the runtime bundled in the dev eclipse IDE. I could fix it in other cases by simply removing the IDE's system repository and will check if that same fix also applies here ASAP, but currently that is "by next week, at the soonest".
