### ISSUE TITLE
metamodel bug related to default constructors

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.language#757]
I get:

```
Exception in thread "main" com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unsupported declaration type: function X.y() => X.y
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1794)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1789)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getJavaMethod(Metamodel.java:809)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.$getJavaAnnotations$(FreeFunction.java:305)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:1103)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:1097)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:362)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:346)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$And.accept(Predicates.java:118)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.filteredMembers(FreeClassOrInterface.java:215)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.annotatedMemberDeclarations(FreeClassOrInterface.java:186)
```

With this class:

```ceylon
class X {
	shared new y() {}
	shared new z(String z) {}
}
```

**Comment by gavinking** [comment]
Also this:

```
Exception in thread "main" com.redhat.ceylon.compiler.java.runtime.metamodel.ModelError: Unsupported declaration type: function Array<T>.ofSize(Integer int, Anything something, T str) => Array<T>.ofSize
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1794)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.newModelError(Metamodel.java:1789)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.getJavaMethod(Metamodel.java:809)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeFunction.$getJavaAnnotations$(FreeFunction.java:305)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:1103)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Metamodel.annotations(Metamodel.java:1097)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:362)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$AnnotatedWith.accept(Predicates.java:346)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.Predicates$And.accept(Predicates.java:118)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.filteredMembers(FreeClassOrInterface.java:215)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassOrInterface.annotatedMemberDeclarations(FreeClassOrInterface.java:186)
```

**Comment by tombentley** [comment]
Fixed
