### ISSUE TITLE
NPE accessing defaultConstructor for an object

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon.language#777]
```ceylon
shared object o { test shared void f() {} }
shared void runo() {
    value x = `class o`;
    print (x.defaultConstructor);
}
```
results in
```
ceylon run: null
java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FunctionalUtil.getParameters(FunctionalUtil.java:19)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeInitializerConstructor.<init>(FreeInitializerConstructor.java:62)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassWithInitializer.getDefaultConstructor(FreeClassWithInitializer.java:76)
```

related to https://github.com/ceylon/ceylon.language/issues/750 and possibly https://github.com/ceylon/ceylon-sdk/issues/430

**Comment by tombentley** [comment]
@gavinking I think the actual problem here is that the type of `class anonymousClass` is `ClassWithInitializerDeclaration`, but according to the spec shouldn't it be `ClassWithConstructorsDeclaration`, since an `object` declaration is an abbreviation of a class with a value constructor?

**Comment by gavinking** [comment]
@tombentley yes, that would be correct now.

**Comment by tombentley** [comment]
Fixed.
