### ISSUE TITLE
NPE in metamodel

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon.language#778]
```
object a {}

shared void test() {
    print(`class a`.defaultConstructor);
}
```
cause
```
java.lang.NullPointerException
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FunctionalUtil.getParameters(FunctionalUtil.java:19)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeInitializerConstructor.<init>(FreeInitializerConstructor.java:62)
	at com.redhat.ceylon.compiler.java.runtime.metamodel.FreeClassWithInitializer.getDefaultConstructor(FreeClassWithInitializer.java:76)
	at bar.test_.test(test.ceylon:4)
	at bar.test_.main(test.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:75)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:122)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:106)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:244)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:491)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
```

**Comment by lucaswerkmeister** [comment]
Dupe of #777?

**Comment by thradec** [comment]
yes, thanks
