### ISSUE TITLE
EnumeratedTypeError: Supposedly exhaustive switch was not exhaustive

### ISSUE THREAD

**Issue by thradec** [ceylon/ceylon.language#779]
I'm not sure where it belongs, so reporting here ...
```
import ceylon.language.meta.declaration {
    ClassDeclaration,
    FunctionDeclaration
}

shared class A {
    shared new() {}    
    shared void b() {}
}

shared void test() {
    
    [FunctionDeclaration, ClassDeclaration?] cd = [`function A.b`, `class A`];
    switch(cd)
    case(is [FunctionDeclaration, ClassDeclaration?]) {
    }
    
}
```
cause
```
Exception in thread "main" com.redhat.ceylon.compiler.java.language.EnumeratedTypeError: Supposedly exhaustive switch was not exhaustive
	at bar.test_.test(test.ceylon:19)
	at bar.test_.main(test.ceylon)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at ceylon.modules.api.runtime.SecurityActions.invokeRunInternal(SecurityActions.java:57)
	at ceylon.modules.api.runtime.SecurityActions.invokeRun(SecurityActions.java:48)
	at ceylon.modules.api.runtime.AbstractRuntime.invokeRun(AbstractRuntime.java:75)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:122)
	at ceylon.modules.api.runtime.AbstractRuntime.execute(AbstractRuntime.java:106)
	at ceylon.modules.Main.execute(Main.java:69)
	at ceylon.modules.Main.main(Main.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.modules.Module.run(Module.java:312)
	at org.jboss.modules.Main.main(Main.java:460)
	at ceylon.modules.bootstrap.CeylonRunTool.run(CeylonRunTool.java:244)
	at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:491)
	at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:380)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:114)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:41)
	at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:34)
	at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:27)
```

**Comment by tombentley** [comment]
That's a bug for ceylon-compiler.

**Comment by FroMage** [comment]
Nevermind where it's filed, I'll take it.

**Comment by FroMage** [comment]
This also works for me, I assume the same issue that caused ceylon/ceylon-model#12 triggered this. Can you reproduce?

**Comment by thradec** [comment]
also unreproducible

**Comment by FroMage** [comment]
Geat!
