### ISSUE TITLE
Serialisation tests fail in JS

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon.language#780]
```
[ceylon-run-js] /home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:263
[ceylon-run-js] if (!cond)throw wrapexc(AssertionError(msg),loc,file);
[ceylon-run-js]                 ^
[ceylon-run-js] ceylon.language::AssertionError "Classes with specified methods cannot be serialized: 'is ReferenceDeclaration attribute' at MemberImpl.ceylon (15:14-15:48)"
[ceylon-run-js]     at AssertionError (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:4862:6)
[ceylon-run-js]     at asrt$ (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:263:25)
[ceylon-run-js]     at MemberImpl$impl_$c$$$a (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1541:58)
[ceylon-run-js]     at MemberImpl$impl_$c$ (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1545:1)
[ceylon-run-js]     at Object.MemberImpl$impl (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:1540:55)
[ceylon-run-js]     at Function.Container.ser$refs$ (/home/stephane/src/java-eclipse/ceylon.language/build/test/serialization/0.1/serialization-0.1.js:77:45)
[ceylon-run-js]     at initializeObject (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:8199:52)
[ceylon-run-js]     at initialize (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:8270:1)
[ceylon-run-js]     at $init$DeserializationContextImpl$serialization.deserializationContextImpl$.reconstruct (/home/stephane/src/java-eclipse/ceylon.language/build/test-repo/ceylon/language/1.1.1/ceylon.language-1.1.1.js:8328:6)
[ceylon-run-js]     at testDeserializationOfObject (/home/stephane/src/java-eclipse/ceylon.language/build/test/serialization/0.1/serialization-0.1.js:278:15)
[ceylon-run-js] ceylon run-js: Node process exited with non-zero exit code: 8
```

**Comment by tombentley** [comment]
Well, that's basically what #775 was about. So I guess the js impl needs to make the same check that the JVM code does, that the member is indeed a `ReferenceDeclaration`.

**Comment by FroMage** [comment]
And where is that done in the JVM?

**Comment by tombentley** [comment]
/ceylon.language/src/ceylon/language/impl/MemberImpl.ceylon

**Comment by FroMage** [comment]
That's not for JVM, that's for both.

**Comment by FroMage** [comment]
Pssst, what's a `ReferenceDeclaration` in the typechecker model?

**Comment by tombentley** [comment]
Well that's what's throwing the exception on JVM, and it's that exception the code is looking for *I believe*. (I don't know from this issue which test is failing). It might be that JS isn't producing something whose runtime type is `ReferenceDeclaration`.

**Comment by tombentley** [comment]
A `Value` is transient=false, iirc

**Comment by tombentley** [comment]
But it's `Unit.getValueDeclarationType()` which decides which meta-type a literal gets.

**Comment by FroMage** [comment]
Well, it's not about literals or such. I think it's that the generated JS code tries to serialise transient values.

**Comment by FroMage** [comment]
Ah no, that was already checked, damnit.

**Comment by FroMage** [comment]
So maybe you're right it's a runtime type issue. Did you add tests for the two different types of metamodels?

**Comment by FroMage** [comment]
It doesn't look like @chochos added any impl of `ReferenceDeclaration` yet. Was that already supposed to be done?

**Comment by tombentley** [comment]
https://github.com/ceylon/ceylon.language/issues/681#issuecomment-146030612

**Comment by FroMage** [comment]
Yeah, bullshit. Plus it's double bullshit because there can't be any tests for this.

**Comment by FroMage** [comment]
OK this is done.
